### ISSUE TITLE
Waiting for test notification with docker-compose and selfhosted ntfy on synology

### ISSUE THREAD

**Issue by samuelps26** [mollyim/mollysocket#44]
In Molly-UP the status says "Waiting for test notification"
I have set up ntfy with docker-compose on my Synology (behind reverse-proxy) an granted user '*' read-write access to up* and the same with the user that is loged in on the ntfy android app.
I also installed mollysocket with docker-compose on Synology (behind reverse-proxy) with this yml:
```
version: "3"

services:
  mollysocket:
    image: ghcr.io/mollyim/mollysocket:latest
    container_name: mollysocket
    restart: always
    volumes:
      - /volume2/docker/mollysocket/data:/data
    working_dir: /data
    command: server
    environment:
      - MOLLY_DB="/data/mollysocket.db"
      # Do not add space in the array ["http://a.tld","*"]
      - MOLLY_ALLOWED_ENDPOINTS=["https://my.ntfy.tld"]
      - MOLLY_ALLOWED_UUIDS=["*"]
      - MOLLY_HOST=0.0.0.0
      - MOLLY_PORT=8020
      - RUST_LOG=info
    ports:
      - "8020:8020"
```
I already tried to re-register the molly-up app by switching to websocket an back to up
