### ISSUE TITLE
Questions about VAPID key and security

### ISSUE THREAD

**Issue by asandikci** [mollyim/mollysocket#49]
Hi, first of all thanks for this excellent project!
I want to ask a few things:

1. What is the VAPID? And what is the use-scenario for it? 

2. When I set up VAPID key, the domain (`molly-socket.domain.tld`) that I've installed molly-socket is showing a qr code / link. What is that? This domain is public and accessible by anyone, is it OK?

3. Is this Molly Socket Server secure to use if both molly-socket domain (`molly-socket.domain.tld`) and push server domain (`mypushserver.domain.tld`) is known by anyone

my configs:
```toml
#...
allowed_endpoints = ['https://mypushserver.domain.tld/']
allowed_uuids = ['bla-bla-bla-bla-account-id-bla-bla-bla']
webserver = true
vapid_privkey = "mollysocket-vapid-gen-command-output-here"
#...
```

Lastly, are there anything that should I consider to make molly-socket/UnifiedPush mechanism more secure/private?

Thanks in Advance
