### ISSUE TITLE
no connection to ipv6 only host?...

### ISSUE THREAD

**Issue by b90g** [mollyim/mollysocket#55]
Using docker and  your compose file. With nextcloud and their uppush app.

Worked prior with molly-unifiedpush app.

stopped working since i updated it.

below:
1. wget connects to ipv6 domain from within the container.
2. getting mollysocket to connect to the domain doesnt work 

Domain is a CNAME, does that have an impact?

```
root@localhost:~# docker exec mollysocket wget https://DOMAIN/index.php/apps/uppush/push/ACCOUNT
--2024-12-04 22:30:15--  https://DOMAIN/index.php/apps/uppush/push/ACCOUNT
Resolving DOMAIN (DOMAIN)... 2a02:acab:acab:acab:acab:acab:acab:acab
Connecting to DOMAIN (DOMAIN)|2a02:acab:acab:acab:acab:acab:acab:acab|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 29 [application/json]
Saving to: 'TOKEN.3'

     0K                                                       100%  138M=0s

2024-12-04 22:30:15 (138 MB/s) - 'TOKEN.3' saved [29/29]

root@localhost:~# docker exec mollysocket mollysocket connection ping uuid-uuid-uuid-uuid-uuid
[2024-12-04T22:30:20Z DEBUG mollysocket::cli] env_logger initialized
[2024-12-04T22:30:20Z INFO  mollysocket::config] No config file supplied
[2024-12-04T22:30:20Z INFO  mollysocket::vapid] VAPID public key: "VAPIDKEY"
[2024-12-04T22:30:20Z DEBUG reqwest::connect] starting new connection: https://DOMAIN/
thread 'main' panicked at src/cli/connection.rs:125:28:
called `Result::unwrap()` on an `Err` value: HTTP status client error (404 Not Found) for url (https://DOMAIN/index.php/apps/uppush/push/ACCOUNT)

Location:
    src/utils.rs:15:5
stack backtrace:
   0:     0x5609f02e30d9 - <unknown>
   1:     0x5609f010c3b3 - <unknown>
   2:     0x5609f02ba0c2 - <unknown>
   3:     0x5609f02e7db2 - <unknown>
   4:     0x5609f02e7c07 - <unknown>
   5:     0x5609f02e82e0 - <unknown>
   6:     0x5609f02e7e88 - <unknown>
   7:     0x5609f02e7de9 - <unknown>
   8:     0x5609f02e7ddc - <unknown>
   9:     0x5609effee3ff - <unknown>
  10:     0x5609effee795 - <unknown>
  11:     0x5609f006d728 - <unknown>
  12:     0x5609f00a7a4b - <unknown>
  13:     0x5609f0020cfe - <unknown>
  14:     0x5609f00a9617 - <unknown>
  15:     0x7fe3a9cdd24a - <unknown>
  16:     0x7fe3a9cdd305 - __libc_start_main
  17:     0x5609effffde1 - <unknown>
  18:                0x0 - <unknown>
```

```
services:
  mollysocket:
    image: ghcr.io/mollyim/mollysocket:1
    container_name: mollysocket
    restart: always
    volumes:
      - ./data:/data
    working_dir: /data
    command: server
    environment:
      - MOLLY_DB="/data/mollysocket.db"
      - MOLLY_ALLOWED_ENDPOINTS=["*"]
      - MOLLY_ALLOWED_UUIDS=["*"]
      - MOLLY_VAPID_PRIVKEY="VAPIDKEY"
      - MOLLY_HOST=0.0.0.0
      - MOLLY_PORT=8020
      - RUST_LOG=debug
      - RUST_BACKTRACE=full
    ports:
      - "8020:8020"
    network_mode: my-network

```

the only thing that differs is my crappy network bridge because stupid docker doesnt expect ipv6 to happen....
