### ISSUE TITLE
Webserver won't start, when using docker-compose

### ISSUE THREAD

**Issue by skyhoppertv** [mollyim/mollysocket#64]
When I start my docker-compose file, it will show the normal logs, but the webserver won't start. nmap also doesn't show, that the port is "active". I tried the three newest versions ([1.5.3](https://github.com/mollyim/mollysocket/releases/tag/1.5.3)-[1.5.5](https://github.com/mollyim/mollysocket/releases/tag/1.5.5)). And nothing's working

```
services:
  mollysocket:
    image: ghcr.io/mollyim/mollysocket:1.5.5-alpine
    container_name: mollysocket
    restart: always
    volumes:
      - ./data:/data
    working_dir: /data
    command: server
    environment:
      - MOLLY_DB="/data/mollysocket.db"
      # Do not add space in the array ["http://a.tld","*"]
      - MOLLY_ALLOWED_ENDPOINTS=["*"]
      - MOLLY_ALLOWED_UUIDS=["*"]
      - MOLLY_HOST=127.0.0.1
      - MOLLY_PORT=8020
      - RUST_LOG=debug
      - MOLLY_VAPID_PRIVKEY=xxxxxxxxxxxxxxxxxx
      - RUST_BACKTRACE=full
      - MOLLY_WEBSERVER=true
    ports:
      - "8020:8020"


```
