### ISSUE TITLE
Support local & remote (dns) names for distributor endpoints

### ISSUE THREAD

**Issue by pimlie** [mollyim/mollysocket#79]
When running both ntfy & mollysocket locally in docker containers, you probably want mollysocket to connect to the ntfy container over the local network. At the moment that means you have to specify a specific (internal) ip address for the ntfy container, then override the hostname of the endpoint with that ip adress as hostname for the mollysocket container.

```yaml
#docker-compose.yml
services:
  ntfy:
    ...
    networks:
      mynet:
        ipv4_address: 172.20.1.5
    ...
  mollysocket:
    ...
    extra_hosts:
      - "ntfy.mydomain.com:172.20.1.5"
```

The reason for that is because mollysocket uses the hostname that the user configured on their phone in ntfy. Which basically is always a publicly available domain name like `ntfy.mydomain.com`. So mollysocket will also try to connect to `ntfy.mydomain.com`. But if you have configured both ntfy & mollysocket in a single docker-compose, then from within mollysocket you could also just immediately connect to `ntfy` (if thats the container name). So it would be nice if the endpoints config could support a remote & local address mapping for each endpoint, as keeping track of ipv4_addresses in larger docker networks is not always easy :)

Maybe use a tuple config option for that, so something like 
```
MOLLY_ALLOWED_ENDPOINTS=["https://ntfy.sh",["https://ntfy.mydomain.com","ntfy"]]
```

**Comment by p1gp1g** [comment]
MOLLY_ALLOWED_ENDPOINT is an _allow_list_ for private IP, so this is unrelated, but I see what you're looking for.

I'm curious, have you tried this ?

```yml
services:
  ntfy.mydomain.com:
    ...
```
