### ISSUE TITLE
Stop receiving notifications after about a week

### ISSUE THREAD

**Issue by eric72777** [mollyim/mollysocket#89]
After about a week, I am unable to receive notifications. Restarting the podman container immediately fixes the issue. I was wondering if anyone else had experienced this issue or had any advice to troubleshoot.

compose.yml
```
  mollysocket:
    image: ghcr.io/mollyim/mollysocket:1
    container_name: mollysocket
    restart: always
    volumes:
      - /mnt/appdata/mollysocket:/data
    working_dir: /data
    command: server
    environment:
      - MOLLY_DB="/data/mollysocket.db"
      - MOLLY_ALLOWED_ENDPOINTS=["*"]
      - MOLLY_ALLOWED_UUIDS=["*"]
      - MOLLY_VAPID_PRIVKEY=<<REDACTED>>
      - MOLLY_HOST=0.0.0.0
      - MOLLY_PORT=8020
      - RUST_LOG=info
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mollysocket.rule=Host(`mollysocket.server.duckdns.org`)"
      - "traefik.http.routers.mollysocket.entrypoints=websecure"
      - "traefik.http.routers.mollysocket.tls=true"
      - "traefik.http.services.mollysocket.loadbalancer.server.port=8020"
networks:
  proxy:
    external: true
```
